run:
  timeout: 2m
  go: '1.19'
  tests: false
  skip-dirs:
    - mocks
    - migrations
linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
  misspell:
    locale: US
  lll:
    line-length: 180
  funlen:
    lines: 200
    statements: 100
  nestif:
    min-complexity: 8
linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - cyclop
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forbidigo
  - funlen
  - ginkgolinter
  - gocheckcompilerdirectives
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - goerr113
  - gofmt
  - goheader
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - lll
  - loggercheck
  - maintidx
  - makezero
  - misspell
  - musttag
  - nakedret
  - nestif
  - nilerr
  - noctx
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tenv
  - testableexamples
  - testpackage
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
issues:
  exclude-rules:
    - text: "%v"
      linters:
        - goerr113
    - text: "File is not `gofmt`-ed with `-s`"
      linters:
        - gofmt
    - text: "SQL string formatting"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - dupl
        - lll
    - path: http
      linters:
        - dupl
    - path: monitor
      linters:
        - containedctx
service:
  golangci-lint-version: 1.51.2 # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"