version: '3'
services:
  templatedb:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: templatedb
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-service-template-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      ENV: dev
    depends_on:
      - templatedb
      - nats
      - jaeger
  jaeger: # Access UI via http://localhost:16686
    image: jaegertracing/all-in-one:1.42
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "9411:9411"
  nats:
    image: nats:2.10.5-alpine3.18
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    volumes:
      - ./data:/nats-server/data
    command: ["-js"]

volumes:
  pgdata: