version: '3'
services:
  templatedb:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: templatedb
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-service-template-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      ENV: dev
    depends_on:
      - templatedb
      - zookeeper
      - kafka
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.42
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
      - "9411:9411"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    expose:
      - 2181
      - 2888
      - 3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: none
  kafka:
    image: confluentinc/cp-kafka:5.4.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG4J_LOGGERS="kafka.controller=WARN,kafka.foo.bar=DEBUG"
      - KAFKA_LOG4J_ROOT_LOGLEVEL=WARN
      - KAFKA_TOOLS_LOG4J_LOGLEVEL=WARN

volumes:
  pgdata: