receivers:
  otlp:
    protocols:
      grpc:
        
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
#    traces:
#      receivers: [otlp]
#      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
#    metrics:
#      receivers: [otlp, prometheus]
#      exporters: [debug]