appConfig:
  version: "1.0"
  name: "go-service-template"
webServerConfig:
  address: 0.0.0.0:8080
  readHeaderTimeout: 1s
kafkaConfig:
  brokers:
    - localhost:9092
  consumerGroup: "go-service-template-dev"
  maxRetries: 3
httpClientConfig:
  locationsDatabaseConnection: "url"
  maxIdleConns: 100
  maxConnsPerHost: 100
  maxIdleConnsPerHost: 50
  idleConnTimeoutSeconds: 90
  requestTimeoutSeconds: 30
dBConfig:
  locationsDatabaseConnection: "postgres://postgres:password@localhost:5432/templatedb?sslmode=disable"
openTelemetryConfig:
  tracesCollectorEndpoint: "http://localhost:14268/api/traces"
  metricsCollectorEndpoint:
  logsCollectorEndpoint: